Task 1
Create a 1D array of numbers from 0 to 9

In [23]:
import numpy as np

In [24]:
array_1 = np.arange(0,10)
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


Task 2
Create a 3×3 NumPy array of all Boolean value Trues

In [25]:

array_2 = np.bool8([True,True,True,True,True,True,True,True,True,])

array_3= array_2.reshape(3,3)
print(array_3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Task 3 
Extract all odd numbers from array of 1-10

In [28]:
import numpy as np
array_4 = np.arange(1,11,2)
array_4= print("Odd numbers from array of 1-10: ", array_4)

Odd numbers from array of 1-10:  [1 3 5 7 9]


Task 4

Replace all odd numbers in an array of 1-10 with the value -1

In [32]:
array_5 = np.ones(10)
#array_replace= np.ones(array_4)
print(array_5)
#print("Odd numbers from array of 1-10: ", array_4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
None


Task 5
Convert a 1D array to a 2D array with 2 rows

In [47]:
# 1 dimensional array [1, 2, 3, 4, 5,6,7,8,]
# Converting 1-dimensional array to 2-D array
array_6 = np.array([1, 2, 3, 4, 5,6,7,8,]).reshape(4,2)

print(array_6)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Task 6
Create two arrays a and b, stack these two arrays vertically use the np.dot and 
np.sum to calculate total

In [72]:
a = np.arange(0,31,2).reshape(4,4)
b = np.arange(3,50,3).reshape(4,4)
c = np.dot(a, b)
print(c)
#print(a)
#b

#total_sum = np.sum(c)
#print(total_sum)


[[ 372  408  444  480]
 [1044 1176 1308 1440]
 [1716 1944 2172 2400]
 [2388 2712 3036 3360]]
